version: 0.0
os: linux
files:
  - source: scripts
    destination: /home/ubuntu/Grupo23-ArquiSoftware/
permissions:
  - object: scripts
    pattern: "**"
    owner: ubuntu
hooks:
  BeforeInstall:
    - location: installDependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: stopServers.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: startServers.sh
      timeout: 300
      runas: ubuntu