version: 0.0
os: linux
files:
  - source: scripts
    destination: /home/ubuntu/Grupo23-ArquiSoftware/scripts
permissions:
  - object: scripts
    pattern: "**"
    owner: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/installDependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stopServers.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/startServers.sh
      timeout: 300
      runas: ubuntu